branch-defaults:
  create-endpoint-for-annotated-frames:
    environment: Parkingspotdetector-env
  main:
    environment: Parkingspotdetector-env
environment-defaults:
  Parkingspotdetector-env:
    branch: null
    repository: null
global:
  application_name: parkingspotdetector
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
